name: SonarQube cloud

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build:
    name: Sonar 
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          
      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet sonarscanner begin /k:"MatchUp" /o:"max668103" /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
          dotnet build MatchUp.sln
          dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
